apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-sample
  labels:
    app: node-sample
  namespace: default
spec:
  progressDeadlineSeconds: 240
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: node-sample
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 35%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-sample
    spec:
      containers:
        - env:
          - name: PORT
            value: "5000"
          name: node-sample
          image: rohith369/node1:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /user
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /details
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 5000
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: rohithdockerlogin
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
