apiVersion: v1
kind: Service
metadata:
  name: node-sample
  labels:
    app: node-sample
spec:
  type: NodePort
  ports:
  - nodePort: 30333
    port: 8080
    targetPort: 5000
    protocol: TCP
  selector:
    app: node-sample
